Importing the libraries

In [211]:
import numpy as np
import pandas as pd

Importing the dataset

In [212]:
data = pd.read_csv(r'../data/StudentsPerformance.csv')

In [213]:
data

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
0,Female,Group B,Bachelors Degree,Standard,Not Completed,72,72,74
1,Female,Group C,College,Standard,Completed,69,90,88
2,Female,Group B,Masters Degree,Standard,Not Completed,90,95,93
3,Male,Group A,Associate Degree,Free/Reduced,Not Completed,47,57,44
4,Male,Group C,College,Standard,Not Completed,76,78,75
...,...,...,...,...,...,...,...,...
995,Female,Group E,Masters Degree,Standard,Completed,88,99,95
996,Male,Group C,High School,Free/Reduced,Not Completed,62,55,55
997,Female,Group C,High School,Free/Reduced,Completed,59,71,65
998,Female,Group D,College,Standard,Completed,68,78,77
999,Female,Group D,College,Free/Reduced,Not Completed,77,86,86

Extracting basic information from the dataset

In [214]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gender                       1000 non-null   object
 1   Race                         1000 non-null   object
 2   Parental_Level_of_Education  1000 non-null   object
 3   Lunch                        1000 non-null   object
 4   Test_Preparation             1000 non-null   object
 5   Math_Score                   1000 non-null   int64
 6   Reading_Score                1000 non-null   int64
 7   Writing_Score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [215]:
data.shape

(1000, 8)

In [216]:
data.size

8000

In [217]:
data.columns

Index(['Gender', 'Race', 'Parental_Level_of_Education', 'Lunch',
       'Test_Preparation', 'Math_Score', 'Reading_Score', 'Writing_Score'],
      dtype='object')

In [218]:
data.isna().sum()

Gender                         0
Race                           0
Parental_Level_of_Education    0
Lunch                          0
Test_Preparation               0
Math_Score                     0
Reading_Score                  0
Writing_Score                  0
dtype: int64

In [219]:
data.describe(include='all')

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
count,1000,1000,1000,1000,1000,1000.00000,1000.000000,1000.000000
unique,2,5,5,2,2,NaN,NaN,NaN
top,Female,Group C,High School,Standard,Not Completed,NaN,NaN,NaN
freq,518,319,375,645,642,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,66.08900,69.169000,68.054000
std,NaN,NaN,NaN,NaN,NaN,15.16308,14.600192,15.195657
min,NaN,NaN,NaN,NaN,NaN,0.00000,17.000000,10.000000
25%,NaN,NaN,NaN,NaN,NaN,57.00000,59.000000,57.750000
50%,NaN,NaN,NaN,NaN,NaN,66.00000,70.000000,69.000000
75%,NaN,NaN,NaN,NaN,NaN,77.00000,79.000000,79.000000
max,NaN,NaN,NaN,NaN,NaN,100.00000,100.000000,100.000000

In [220]:
data.dtypes

Gender                         object
Race                           object
Parental_Level_of_Education    object
Lunch                          object
Test_Preparation               object
Math_Score                      int64
Reading_Score                   int64
Writing_Score                   int64
dtype: object

Renaming every column

In [221]:
data.rename(columns={
    'gender':'Gender',
    'race/ethnicity':'Race',
    'parental level of education':'Parental_Level_of_Education',
    'lunch':'Lunch',
    'test preparation course':'Test_Preparation',
    'math score':'Math_Score',
    'reading score':'Reading_Score',
    'writing score':'Writing_Score'
}, inplace=True)

In [222]:
data.head()

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
0,Female,Group B,Bachelors Degree,Standard,Not Completed,72,72,74
1,Female,Group C,College,Standard,Completed,69,90,88
2,Female,Group B,Masters Degree,Standard,Not Completed,90,95,93
3,Male,Group A,Associate Degree,Free/Reduced,Not Completed,47,57,44
4,Male,Group C,College,Standard,Not Completed,76,78,75

Working with Gender column

In [223]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [224]:
data['Gender'] = data['Gender'].str.title()

In [225]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [226]:
data.head()

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
0,Female,Group B,Bachelors Degree,Standard,Not Completed,72,72,74
1,Female,Group C,College,Standard,Completed,69,90,88
2,Female,Group B,Masters Degree,Standard,Not Completed,90,95,93
3,Male,Group A,Associate Degree,Free/Reduced,Not Completed,47,57,44
4,Male,Group C,College,Standard,Not Completed,76,78,75

Working with Race column

In [227]:
data['Race'].unique()

array(['Group B', 'Group C', 'Group A', 'Group D', 'Group E'],
      dtype=object)

In [228]:
data['Race'] = data['Race'].str.title()

In [229]:
data['Race'].unique()

array(['Group B', 'Group C', 'Group A', 'Group D', 'Group E'],
      dtype=object)

Working with Parental_Level_of_Education column

In [230]:
data['Parental_Level_of_Education'].unique()

array(['Bachelors Degree', 'College', 'Masters Degree',
       'Associate Degree', 'High School'], dtype=object)

In [231]:
data["Parental_Level_of_Education"] = (
    data["Parental_Level_of_Education"].replace({
        "some college": "college",
        "bachelor's degree": "bachelors degree",
        "master's degree": "masters degree",
        "associate's degree": "associate degree",
        "some high school": "high school"
    }))

In [232]:
data['Parental_Level_of_Education'] = data['Parental_Level_of_Education'].str.title()

In [233]:
data.head()

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
0,Female,Group B,Bachelors Degree,Standard,Not Completed,72,72,74
1,Female,Group C,College,Standard,Completed,69,90,88
2,Female,Group B,Masters Degree,Standard,Not Completed,90,95,93
3,Male,Group A,Associate Degree,Free/Reduced,Not Completed,47,57,44
4,Male,Group C,College,Standard,Not Completed,76,78,75

Working with Lunch column

In [234]:
data['Lunch'].unique()

array(['Standard', 'Free/Reduced'], dtype=object)

In [235]:
data['Lunch'] = data['Lunch'].str.title()

In [236]:
data.head()

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
0,Female,Group B,Bachelors Degree,Standard,Not Completed,72,72,74
1,Female,Group C,College,Standard,Completed,69,90,88
2,Female,Group B,Masters Degree,Standard,Not Completed,90,95,93
3,Male,Group A,Associate Degree,Free/Reduced,Not Completed,47,57,44
4,Male,Group C,College,Standard,Not Completed,76,78,75

Working with Test_Preparation column

In [237]:
data['Test_Preparation'].unique()

array(['Not Completed', 'Completed'], dtype=object)

In [238]:
data['Test_Preparation'] = data['Test_Preparation'].str.title()

In [239]:
data['Test_Preparation'] = data['Test_Preparation'].fillna('Not Completed')

Seeing the final data

In [240]:
data.head()

,Gender,Race,Parental_Level_of_Education,Lunch,Test_Preparation,Math_Score,Reading_Score,Writing_Score
0,Female,Group B,Bachelors Degree,Standard,Not Completed,72,72,74
1,Female,Group C,College,Standard,Completed,69,90,88
2,Female,Group B,Masters Degree,Standard,Not Completed,90,95,93
3,Male,Group A,Associate Degree,Free/Reduced,Not Completed,47,57,44
4,Male,Group C,College,Standard,Not Completed,76,78,75

Saving the file

In [241]:
data.to_csv(r'StudentsPerformance.csv', index=False)